In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns

In [4]:
df = sns.load_dataset('iris')

In [6]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['species'] = le.fit_transform(df[['species']])

c:\Users\ganam\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        0
146           6.3          2.5           5.0          1.9        0
147           6.5          3.0           5.2          2.0        0
148           6.2          3.4           5.4          2.3        0
149           5.9          3.0           5.1          1.8        0

[150 rows x 5 columns]

In [46]:
X = df.iloc[:, 0:4] 
y = df.iloc[:, -1] 
y.shape

(150,)

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [49]:
clf1 = LogisticRegression()
clf2 = KNeighborsClassifier()
clf3 = RandomForestClassifier()

In [50]:
estimators = [('lr',clf1), ('rf', clf3), ('knn', clf2)]

In [52]:
for estimator in estimators:
    x = cross_val_score(estimator[1],X,y,cv=10,scoring='accuracy')
    print(estimator[0],np.round(np.mean(x),2))

lr 1.0
rf 1.0
knn 1.0

In [57]:
# Hard Voting 

from sklearn.ensemble import VotingClassifier
vc = VotingClassifier(estimators=estimators)

x = cross_val_score(vc, X , y , cv =10 , scoring='accuracy')

print(np.round(np.mean(x), 2))

1.0

In [ ]:
vc1 = VotingClassifier(estimators=estimators, voting='soft')

x = cross_val_score(vc1 , X, y , cv = 10 , scoring='accuracy')
print(np.round(np.mean(x), 2))

1.0